version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python (pip requirements.txt)
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"

  # Terraform (optional — depends on how strict you want IaC deps)
  - package-ecosystem: "terraform"
    directory: "/infra/terraform"
    schedule:
      interval: "weekly"