version: "3.8"
services:
  web:
    build:
      context: ../app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 5s
      timeout: 2s
      retries: 10