name: ZAP Baseline Scan

on:
  push:
  pull_request:

jobs:
  zap:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If your app needs to be running before ZAP scans it, spin it up here:
      - name: Start app with docker-compose
        run: |
          docker compose -f infra/docker-compose.ci.yml up -d
          echo "Waiting for health check at http://localhost:8000/health..."
          for i in $(seq 1 60); do
            CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health || true)
            if [ "$CODE" = "200" ]; then
              echo "App is healthy."
              exit 0
            fi
            sleep 2
          done
          echo "App failed to start in time."
          docker compose -f infra/docker-compose.ci.yml logs --no-color || true
          exit 1

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'http://localhost:8000'
          rules_file_name: 'zap-baseline.conf'
          cmd_options: '-a'  # active scan lite

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-${{ github.sha }}
          path: report_html.html
          if-no-files-found: warn
          retention-days: 7

      - name: Stop app
        if: always()
        run: docker compose -f infra/docker-compose.ci.yml down -v