name: ZAP Baseline Scan

on:
  push:
  pull_request:

jobs:
  zap:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you need to spin up your app for scanning, do it here:
      # - name: Start app (example)
      #   run: |
      #     docker-compose -f infra/docker-compose.ci.yml up -d
      #   shell: bash

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8000'
          rules_file_name: 'zap-baseline.conf'
          cmd_options: '-a' # add active scan lite

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-${{ github.sha }}
          path: report_html.html
          retention-days: 7